### ISSUE TITLE
Adding the FAIR metrics manuscript to the catalog

### ISSUE THREAD

**Issue by dhimmel** [manubot/catalog#6]
@sbonaretti's manuscript titled "Two real use cases of FAIR maturity indicators in the life sciences" is now on bioRxiv at https://doi.org/10.1101/739334. The source repo is at https://github.com/sbonaretti/FAIR_metrics.

Serena used a modified manubot setup where the manuscript was built locally rather than using CI. The repo doesn't host an HTML version of the manuscript via GitHub pages. Our software to populate the catalog from `catalog.yml` requires a `html_url` I believe to retrieve metadata. Possibly we could use https://rawcdn.githack.com/sbonaretti/FAIR_metrics/c12a837e1b0505ffa7a3cd311e3fa69b5b940d2e/paper/manubot/webpage/v/local/index.html, which seems to produce correct metadata:

<details>

```
manubot cite url:https://rawcdn.githack.com/sbonaretti/FAIR_metrics/c12a837e1b0505ffa7a3cd311e3fa69b5b940d2e/paper/manubot/webpage/v/local/index.html
```
```json
[
  {
    "id": "1Hl6qxW9W",
    "type": "webpage",
    "title": "Two real use cases of FAIR maturity indicators in the life sciences",
    "URL": "https://rawcdn.githack.com/sbonaretti/FAIR_metrics/c12a837e1b0505ffa7a3cd311e3fa69b5b940d2e/paper/manubot/webpage/v/local/index.html",
    "language": "en-US",
    "author": [
      {
        "family": "Bonaretti",
        "given": "Serena"
      },
      {
        "family": "Willighagen",
        "given": "Egon"
      }
    ],
    "issued": {
      "date-parts": [
        [
          "2019",
          8,
          11
        ]
      ]
    },
    "accessed": {
      "date-parts": [
        [
          "2019",
          9,
          3
        ]
      ]
    },
    "note": "This CSL JSON Item was automatically generated by Manubot v0.2.3 using citation-by-identifier.\nstandard_id: url:https://rawcdn.githack.com/sbonaretti/FAIR_metrics/c12a837e1b0505ffa7a3cd311e3fa69b5b940d2e/paper/manubot/webpage/v/local/index.html"
  }
]
```
</details>

Also there are some nice figures in the manuscript. @vincerubinetti did you want to create a PNG screenshot that we could drag into this issue and use as the thumbnail?

**Comment by vincerubinetti** [comment]
![image](https://user-images.githubusercontent.com/8326331/64188347-3ab9e180-ce40-11e9-9f82-aa3f11223f73.png)

**Comment by dhimmel** [comment]
Added to the catalog in e7c7e367cf77a5acc6061e128262e76040521692. Now visible at https://manubot.org/catalog/

> ![image](https://user-images.githubusercontent.com/1117703/64191753-2b8a6200-ce47-11e9-8153-a1c8dd31b2bb.png)

Note that the way we added the `html_url` is versioned, so if the manuscript is updated, our script won't automatically get the new metadata. So @sbonaretti let us know if there's an udpate or submit a PR to update the githack.com URL:

https://github.com/manubot/catalog/blob/e7c7e367cf77a5acc6061e128262e76040521692/catalog.yml#L82
